### ISSUE TITLE
Stripe Module Bug

### ISSUE THREAD

**Issue by pigipi** [Dolibarr/dolibarr#16067]
Hey there,

I found a bug with the Stripe module. Apparently the Stripe module is always using the same Idempotent key for an invoice. But it has to be always a different one, or Stripe servers refuse the payment. 
Today, the Idempotent key is related to the description field sent by POST and it's always the same description. If we added only a timestamp at the end of the description related to the payment timestamp, the problem is resolved. 

Here is the Idempotent doc => https://stripe.com/docs/api/idempotent_requests

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **PHP**: 7.4
- **Database**: 5.6 Apache

## Steps to reproduce the behavior
Fail a payment, then try to pay it again, it will fail all the time. Stripe will refuse all payments.

**Comment by TomBoss** [comment]
Same issue. After a failing payment with Stripe, I have to re-save the invoice for the payment to work.

## Environment
* **Version**: 12.0.4
* **OS**: Linux
* **PHP**: 7.4
* **Database**: MariaDB 10.2

**Comment by eldy** [comment]
Can't reproduce with v13. If you can, can you describe how you process to reproduce ?
which url did you use to enter the payment page of invoice ?

**Comment by pigipi** [comment]
I copy/paste Stripe Dev's response about the bug. It's in French, because they used an automated translation. But I think it won't be a problem for you! 

_Après recherches, il semblerait que la majorité des erreurs soient liées à un problème de clé d'idempotence._ 

__Les clés d'idempotence sont des outils très utiles pour éviter les doublons de paiements. Au moment de l'achat d'un client, une requête API est envoyée au serveur Stripe, nous permettant de traiter le mouvement. Des problèmes de réseaux ou ralentissements peuvent causer un double envoi de ces requêtes API, qui entraîneront un doublon de paiement._

_La meilleure défense contre ces événements sont les clés d'idempotence. Chaque requête API peut bénéficier d'une clé unique, qui garantira le traitement d'une seule requête, même en cas de problème réseau. Toute requête qui utilise la même clé d'idempotence qu'une requête reçue précédemment sera ignorée.__

_Sur les requêtes envoyées par Dolibarr, des informations sont envoyées dans la description du paiement. Je remarque que vous passez cette information également comme clé d'idempotence. En soi, ceci n'est pas un problème, du moment que chacune de ces descriptions sont différentes. Le problème est que ces clés ne sont pas utilisées qu'une fois, et les erreurs proviennent du fait que les mêmes clés d'idempotence sont utilisées sur plusieurs paiements._ 

So in fact, if someone failed his payment a first time, he cannot pay again because Dolibarr used the same Idempotent key. That's why I suggest the adding of a timestamp in the key Idempotent field. So it will be description + timestamp. Is it more clear like this? (not sure)

**Comment by pigipi** [comment]
_If you can, can you describe how you process to reproduce ?_

1. Send a URL payment to a user
2. User tries to pay and fails (most of the time because his bank is not ready for double authentification (new SCA system on Stripe), or his bank account is not configured for double-auth)
3. User calls his bank to activate double-auth
4. User tries to pay again = FAIL (same Idempotent key, so payment is refused by Stripe)

_which url did you use to enter the payment page of invoice ?_
Here is an example of URL. But, in my opinion, it is not related to URL. 
/public/payment/newpayment.php?source=invoice&ref=FA2101-XXXX&securekey=xxxxxxxx

**Comment by eldy** [comment]
A fix has been pushed into 13.0 branch. You can try with last 13.0 branch

**Comment by pigipi** [comment]
Thanks. I will update Dolibarr and try.

**Comment by daraelmin** [comment]
Hi @pigipi, hi @atm-quentin,

Is this one closed in 12.0.5 ? I can not find any PR related in v12.

Cheers

**Comment by pigipi** [comment]
The problem is still here. 
The keys for idempotent are still unique, and are not updated after a first attempt to pay. It has to be different for each new payment request even if the invoice ref is the same. 
I tried with 13.0.2 and 13.0.3, not working in both version.

About event object => https://stripe.com/docs/api/events/object#event_object-request-id

idempotency_error | Idempotency errors occur when an Idempotency-Key is re-used on a request that does not match the first request's API endpoint and parameters.
-- | --

**Comment by pigipi** [comment]
I suggest to anyone to use Paybox or Paypal for your payments on Dolibarr. These other platforms are working and have not bug. Stripe plugin is not working and apparently no developer is working on it. So to avoid any payment problems, you should use Paybox or Paypal.

**Comment by hregis** [comment]
@pigipi 
I use Stripe module and it works fine !!!

**Comment by daraelmin** [comment]
@pigipi, Stripe work like a charm on my dolibarr

**Comment by pigipi** [comment]
Yes it is working, if your client can pay for the first attempt. If the first attempt failed, it is done :) and not working anymore. So no, it is not working...

**Comment by pigipi** [comment]
Have a look on Google about this error, and you will understand what I'm explaining since January 21: Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than 'xxxxxxxxx' if you meant to execute a different request.

**Comment by freechelmi** [comment]
Hi , 

just to say I had the exact problem today ( 14.0.5 ) : 

- the client did not suceed his SCA auth 
- now we get the described error when we try again
![image](https://user-images.githubusercontent.com/446021/158615747-0fc49e33-c3eb-4c85-8c54-d27b4519e240.png)


ANybody is working on this ? Let me know if If should dig a bit as the stripe plugin is really important to us

**Comment by daraelmin** [comment]
Hi @freechelmi,

Maybe @ptibogxiv can help you.

Cheers

**Comment by ptibogxiv** [comment]
@daraelmin @freechelmi  You can use this hidden option

STRIPE_REUSE_EXISTING_INTENT_IF_FOUND

**Comment by freechelmi** [comment]
Thanks , is this the same as adding &noidempotency=1 to urls ?

**Comment by ptibogxiv** [comment]
No With this, you will have idempotency key but the payment intention will be reuse and not Generate again with bugs.

Idempotency key must be use in order to avoir duplicate payment

**Comment by erwinpalma** [comment]
I had the same issue and I created a workaround (if you still neede it), I tested with the Dolibarr version 18.0.1, but I assume that could be integrated with other version

random_string

1. Into the file `htdocs/core/lib/functions2.lib.php:34` I have added the following function

```php
/**
 * @param	string	$length		length of the string
 * @return	string				random string
 */
function random_string($length) {
    $str = random_bytes($length);
    $str = base64_encode($str);
    $str = str_replace(["+", "/", "="], "", $str);
    $str = substr($str, 0, $length);
    return $str;
}
```

2. Into the file `htdocs/public/payment/newpayment.php` locate the line `$fulltag = 'INV='.$invoice->id.'.CUS='.$invoice->thirdparty->id;` (line 1181 in Dolibarr 18.0.1) and replace it for` $fulltag = 'NO='.random_string(5).'.INV='.$invoice->id.'.CUS='.$invoice->thirdparty->id;`

```php
if (GETPOST('fulltag', 'alpha')) {
		$fulltag = GETPOST('fulltag', 'alpha');
	} else {
		// $fulltag = 'INV='.$invoice->id.'.CUS='.$invoice->thirdparty->id;
		
		$fulltag = 'NO='.random_string(5).'.INV='.$invoice->id.'.CUS='.$invoice->thirdparty->id;
		if (!empty($TAG)) {
			$tag = $TAG; $fulltag .= '.TAG='.$TAG;
		}
	}
```

And then test it

**Comment by gigarun** [comment]
@erwinpalma is there a pull request validated for u'r workaround ? for a définitve resolution ? For my case it didn't work (partial white page without payment infos and options)
17.0.3 the problem already exist
i'm trying @ptibogxiv hidden option. But i have "Field 'tms' doesn't have a default value" error message. 
@atm-quentin tested with https://github.com/Dolibarr/dolibarr/pull/16332/files workaround. Added the line "$description .= ' TIME : '.time();" error message "Field 'tms' doesn't have a default value" still apears but the payment is done. 
Partial solution, not totaly solved for me.

**Comment by ptibogxiv** [comment]
Please contact @eldy this default behaviour is not my choice...

You can fix it by a secret hidden option for reuse stripe intent and avoir double payment:

STRIPE_USE_INTENT_WITH_AUTOMATIC_CONFIRMATION

**Comment by ptibogxiv** [comment]
Please contact @eldy this default behaviour is not my choice...

You can fix it by a secret hidden option for reuse stripe intent and avoir double payment:

STRIPE_USE_INTENT_WITH_AUTOMATIC_CONFIRMATION

**Comment by gigarun** [comment]
Done. Tested with originals php files. Works but message "Field 'tms' doesn't have a default value" still présent.

**Comment by PascalB67** [comment]
Hello, same problem in Dolibarr 18.04 (PHP 8.1) and use STRIPE_USE_INTENT_WITH_AUTOMATIC_CONFIRMATION = 1 
has no effect !?
We test with :STRIPE_REUSE_EXISTING_INTENT_IF_FOUND = 1 and it's no warning
