### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by veasio** [Dolibarr/dolibarr#16091]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Assistant export ne fonctionne plus en V13

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.20
- **Database**: MySQL or MariaDB 5.6.50-log
- **URL(s)**: /exports/export.php?step=5&datatoexport=adherent_1

## Expected and actual behavior
[*Verbose description*]
arrivé à la dernière étape aucun fichier n'est généré ou lien pour télécharger

## Steps to reproduce the behavior
[*Verbose description*]
faire un export des emails (seulement) des adhérents en suivant l'assistant
![Capture d’écran 2021-01-28 à 16 36 18](https://user-images.githubusercontent.com/69649067/106161218-00648900-6187-11eb-8f59-b6e40569937c.png)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Tihs has been fixed into v13 branch for v13.0.1

**Comment by NHC390** [comment]
Where can i find the v13.0.1 for download and implementation?

**Comment by ksar-ksar** [comment]
You can download it from GIT : 
![image](https://user-images.githubusercontent.com/35605507/108085447-a106e400-7075-11eb-81c4-7bf79970e5d2.png)

**Comment by NHC390** [comment]
I have updated the version to 13.0.1 but still have the same issue, there no option to proceed from step-2 to step-3.
Please advise what has to be followed in particular.
![image](https://user-images.githubusercontent.com/79080211/108362751-91ba9e80-720d-11eb-81b8-6cad29a90758.png)
