### ISSUE TITLE
Create inventory permission missing  with possible FIX

### ISSUE THREAD

**Issue by jobrien2001** [Dolibarr/dolibarr#29079]
### Bug

On a clean install, versions 18 and 19 create permission is not available for inventory in user permissions

I beleive this section of code could be responsible for it.

[ $this->rights[6][1] = 'inventoryDeletePermission'; // Permission label ](https://github.com/Dolibarr/dolibarr/blob/1b98d99434cdd7e3b3bf99dca86de1cde5e3b7d0/htdocs/core/modules/modStock.class.php#L165)

First observation: entry number 6,  shouldnt it be 7?  it overwrites the previous entry for inventoryCreatePermission which is already 6.

[ $this->rights[6][1] = 'inventoryCreatePermission'; // Permission label](https://github.com/Dolibarr/dolibarr/blob/1b98d99434cdd7e3b3bf99dca86de1cde5e3b7d0/htdocs/core/modules/modStock.class.php#L159)

Second observation, this entry is a duplicate as it already exists on 
[ $this->rights[10][1] = 'inventoryDeletePermission'; // Permission label ](https://github.com/Dolibarr/dolibarr/blob/1b98d99434cdd7e3b3bf99dca86de1cde5e3b7d0/htdocs/core/modules/modStock.class.php#L185)

When I comment out this array entry section the create permission button will show in user permissions along with a double delete entry

![image](https://github.com/Dolibarr/dolibarr/assets/12868319/9ff312e9-d40b-44f4-af2d-e8e6d5d3870f)

### Dolibarr Version

19.0,18.0

### Environment PHP

8.1

### Environment Database

mariadb

**Comment by hregis** [comment]
@jobrien2001 it's fixed with this PR https://github.com/Dolibarr/dolibarr/pull/29080
thank you

**Comment by jobrien2001** [comment]
@hregis Did you see the double entry for the delete inventory permission? is this intended?

**Comment by hregis** [comment]
@jobrien2001 yes you right, it's fixed, thanks

**Comment by jobrien2001** [comment]
@hregis Thanks for the quick fix.

There is another issue related to this.

Even with this change the permission still shows a duplicate.

![image](https://github.com/Dolibarr/dolibarr/assets/12868319/703be58f-5e16-400a-913e-c1c305986232)

I checked the db and there is still a record of 1016 in the rights_def table.

![image](https://github.com/Dolibarr/dolibarr/assets/12868319/23b366c3-330d-44da-833a-7c2352e2a40c)

I deleted the line and the problem is gone... but I'm not sure if deleting the line will break code relying on this ID.

Can you suggest if this is ok?  Or is there a command to rebuild this table?

**Comment by hregis** [comment]
@jobrien2001 you can try to disable/enable the module

**Comment by jobrien2001** [comment]
@hregis that refreshed all the stock permission.  

I'll report back if I find anything else.

Thank you.
