### ISSUE TITLE
invoiced filter for list of supplier orders does not work

### ISSUE THREAD

**Issue by andreash-esp** [Dolibarr/dolibarr#35434]
### Bug

Filtering supplier orders for not invoiced orders does not work any more.

### Dolibarr Version

22.0.1

### Environment PHP

 7.2.24-0ubuntu0

### Environment Database

mysqlnd 5.0.12-dev

### Attached files

Filter the supplier orders list by "invoiced". This does not change the result if set to "Nein".
Setting to "Ja" works fine.
https://dolibarr.company.de/fourn/commande/list.php

<img width="2160" height="474" alt="Image" src="https://github.com/user-attachments/assets/d2fc5bea-05a9-4863-84fa-4c63b11a80dc" />

**Comment by bchanudet** [comment]
Hello, 

I've been trying to reproduce this bug on 22.0.1 but I can't. Filtering by "No" in the Billed column works as intended. 

In fact it seems it was a problem before but it was fixed by a PR : https://github.com/Dolibarr/dolibarr/commit/f66e9553d5a83f1a87b271c82f554019a5e2e7c1#diff-a8211fa4e79248105750a0cbd8e5964f643e399e596377cf669f9e288cb437dfR885

Before v22, the condition on the SQL query was only added when you filter by "Yes", but now it should be added in both cases.

Could you check if you are really in v22.0.1?

**Comment by andreash-esp** [comment]
<img width="175" height="57" alt="Image" src="https://github.com/user-attachments/assets/fb299618-01bf-45f7-b78f-b77f8e6367b3" />

I'm pretty sure this was working before the update to 22.0.1.

**Comment by bchanudet** [comment]
Hello, 

Indeed, my assumptions were wrong, the code was already working correctly in v21. My bad.

However, here is a video of me trying to reproduce the bug you encounter on v22 but to no avail. Is there something I'm doing wrong here? I'm testing on PHP 8.2, that might be the difference.

https://github.com/user-attachments/assets/06b437d9-8a1a-470a-a92d-6e6038dc5aee

**Comment by andreash-esp** [comment]
Hi, this is exactly what we do. I also tried to change the language to englisch, but the error persists in my installation.

Unfortunately I'm still on Ubuntu Buster, there is no quick way to move to php8.2, I will try to migrate to a current system, but this will take some time.

Many thanks for your efforts!
Andreas

**Comment by pixodeo** [comment]
Read the code path - the SQL guard at htdocs/fourn/commande/list.php:903-904 reads `if (\$billed != \\ && \$billed != \-1\) { \$sql .= \" AND cf.billed = \".((int) \$billed); }`. With `\$billed = \0\` (what the form posts when 'Nein' is selected), both checks are true and `AND cf.billed = 0` is added to the SQL. Verified in Docker with `GETPOST(billed,int)` and PHP 8.

So the filter clause IS appended for 'Nein' on a vanilla install. Two things that would make 'Nein' still match the same rows as no filter:

1. Your `llx_commande_fournisseur.billed` column has NULL values from legacy data (the schema default is 0 but older rows could have been left NULL). `cf.billed = 0` excludes NULL rows, so when most of your unbilled orders are NULL the 'Nein' filter looks like it returns nothing useful. Check: `SELECT COUNT(*) FROM llx_commande_fournisseur WHERE billed IS NULL`.
2. A custom module hooking `printFieldListWhere` is overriding/removing the clause. Check what shows up in your debug log after executing the query.

If (1) is your situation, the right fix is either (a) a one-shot UPDATE to normalize NULL -> 0, or (b) loosen the SQL to `(cf.billed = 0 OR cf.billed IS NULL)`. I'm happy to push (b) - want me to?

**Comment by pixodeo** [comment]
Looked at the chain. htdocs/fourn/commande/list.php:146 reads `$billed = GETPOST('billed', 'int')` with the inline note "Value '' must be possible". `GETPOST(..., 'int')` never returns the empty string though: it returns 0 when the param is absent and 0 when the param is the literal "0" (the "No" choice from selectyesno). Both cases collide.

Then line 903 guards with `if ($billed != '' && $billed != '-1')`. The behaviour of that guard with `$billed = 0` depends on PHP version:
- PHP 8.0+: `0 != ''` is **true** (string and int are no longer loose-equal), so the SQL filter is applied and the "No" choice works.
- PHP 7.x: `0 == ''` is **true** (loose-equal under old rules), so the guard is false and the SQL filter is never appended; the "No" choice has no effect.

You are on PHP 7.2.24, which is past N-2 (current N-2 is PHP 8.x against Dolibarr 22.0 / 23.0 / develop). On supported PHP versions, the filter works as designed.

Two options:
1. Upgrade to PHP 8.x - this fixes your symptom without any code change.
2. If you want robustness across PHP versions, the line 146 cast should switch to `'intcomma'` (which preserves the empty string) and line 903 should use `!== ''` strict, mirroring the `statut` case at line 907 in the same file. I am happy to send that PR if a maintainer agrees; otherwise the natural answer is upgrade.

@eldy any preference?

**Comment by andreash-esp** [comment]
Confirmed, Update to php 8.5 has fixed the issue.

**Comment by pixodeo** [comment]
Glad it works for you now. For the record on why the PHP version changed the outcome: `$billed = GETPOST('billed', 'int')` forces an int, so the "not billed" choice (0) becomes the int 0, and the guards use `if ($billed != '')`. Under older PHP, `0 != ''` was false (0 == ''), so the not-billed filter was silently skipped; PHP 8's stricter number/string comparison makes `0 != ''` true, which is why 8.5 "fixed" it.

The underlying code is still fragile though: because GETPOST('int') collapses an empty value to 0, "no filter" ('') and "not billed" (0) can't be distinguished cleanly - the `!= ''` test only happens to work now thanks to the comparison change. A robust fix would read $billed without forcing 'int' (so '' stays '') rather than relying on loose comparison. Leaving this note in case a maintainer wants to harden it; not urgent since your case is resolved.

**Comment by pixodeo** [comment]
I could not reproduce this from the code, so I need a bit more from you to go further.

On 22.0.1, the version you reported, the filter is applied like this (fourn/commande/list.php:887):

    if ($billed != '' && $billed != '-1') {
        $sql .= " AND cf.billed = ".((int) $billed);
    }

and the combo submits 1 for Yes and 0 for No. I checked what each submitted value produces:

    no filter        billed=''    filter not applied
    empty option     billed=-1    filter not applied
    Yes              billed=1     AND cf.billed = 1
    No               billed=0     AND cf.billed = 0

so selecting No does add the condition, which was my first suspicion (a PHP 8 loose comparison swallowing the 0) and it turned out to be wrong. The code is also identical between 22.0.1 and the current 22.0 branch, so nothing was fixed or broken in between.

Three things would tell me where to look:

1. What exactly do you see: all orders regardless of the filter, no orders at all, or the filter resetting itself after you apply it?
2. Does the URL contain billed=0 after you apply it? If the parameter is absent, the problem is on the form side rather than in the query.
3. Do you use this list through a saved filter or a menu entry with predefined parameters? Those can inject a different value for billed.

Also worth noting: cf.billed is a database column, so an order only counts as invoiced if that flag was actually set. If your orders were invoiced by a route that does not update it, the filter would look broken while doing exactly what it is told. Comparing what you expect with what SELECT rowid, ref, billed FROM llx_commande_fournisseur returns would settle that quickly.

@andreash-esp the report has no reproduction steps, so any patch I wrote now would be a guess.

**Comment by pixodeo** [comment]
I could not reproduce this from the code, so here is what I verified, in case it helps narrow it down.

The filter itself handles all four values correctly (fourn/commande/list.php:911):

    if ($billed != '' && $billed != '-1') {
        $sql .= " AND cf.billed = ".((int) $billed);
    }

Tested with the real GETPOST:

    posted "0"  -> applies AND cf.billed = 0     the not-invoiced filter
    posted "1"  -> applies AND cf.billed = 1
    posted "-1" -> no filter, correct
    posted ""   -> no filter, correct

and the selector that produces those values also behaves correctly (form->selectyesno with useempty):

    no filter set      -> empty option selected
    user picked No     -> No selected
    user picked Yes    -> Yes selected

So on 24.0 the whole path looks sound. Two things would help:

1. What exactly do you see? Does the list come back unfiltered, showing invoiced orders as well, or does it come back empty, or does the selector reset itself after you submit? Those are three different problems.
2. Does the URL after submitting contain billed=0? If it does not, the value never reaches the filter and the issue is in the form submission rather than the query.

Worth noting your environment as well: PHP 7.2.24 is well below what Dolibarr 22 targets, and 22.0.1 is an early point release. If you can retest on a current 22.0.x with a supported PHP, that would rule out a lot at once.

@andreash-esp without one of those details I cannot tell whether this is still present, since the code I can read does the right thing.
