### ISSUE TITLE
Bug: Modifying/deleting Supplier Invoice, Stock do not decrease from Warehouse

### ISSUE THREAD

**Issue by mudassar791** [Dolibarr/dolibarr#7650]
# Bug
When Supplier invoice is deleted, stock of this invoice do not decreased, same if supplier invoice is modified, upon re validation each time stock increases, mean by editing a invoice three time, stock will increase three time. 
## Environment
- **Version**: 6.0.0
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/fourn/facture/card.php?facid=95

**Comment by mudassar791** [comment]
I dont know why people here dont discuss critical and business core bugs, whereas many discussions are found even on "spelling mistake" etc.

**Comment by ruistrecht-alt** [comment]
If you selected "Yes" on "Decrease real stocks on customers invoices/credit notes validation" than this could only be achieved by validating a modified invoice. I haven't tested this yet, but if you re-validate a modified invoice does it re-increase the stock? Or does it update the stock to match the validated modifications?

The workarounds would be:

- Creating a new shipment that indicates that there was indeed a stock decrease with "Decrease real stocks on shipping classification closed" or "Decrease real stocks on shipping validation" options.
- Manually changing the stock to match the real one.

**Comment by mudassar791** [comment]
I'm not talking about customers invoice, The scenario in Customer Invoice is OK.
but there is problem in supplier invoice.

If the supplier invoice is modified =No stock change, on re validation again increase updated stock
If the customer invoice is modified=increase stock, on re validation decrease updated stock.

**Comment by BebZ** [comment]
Maybe the people haven't tested it yet or not taken time to report the bug.
Even if you report a bug, you should post screenshots to prove it.
and sometimes bugs are corrected on 5.0 version and re appear by magic on 6.0...

**Comment by ruistrecht-alt** [comment]
I agree with @BebZ can you, @mudassar791, make a gif detailing the process? It would be easier to understand and replicate.

**Comment by mudassar791** [comment]
![stock do not decrease when invoice is reversed](https://user-images.githubusercontent.com/32223328/31724886-c2814570-b3d7-11e7-995a-30c70a89f00f.png)

**Comment by mudassar791** [comment]
![stocks](https://user-images.githubusercontent.com/32223328/31725167-7fc845a2-b3d8-11e7-9b04-0d5284b8cd4f.png)

I have also settings while stock movement on Invoice validation.
Scenario with customer invoice is OK vice versa.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/7677

**Comment by eldy** [comment]
Fixed by #7677

**Comment by cesar-bsd-com-br** [comment]
I have the same problem now, with version 15.0.1.

I've created a supplier invoice, and validate it - stocks increase OK.

When I delete the invoice, the stocks are the same - Dolibarr didn't decrease.

My configuration is to increase stock when validate the supplier invoice.
![Animação (1)](https://user-images.githubusercontent.com/59903458/170044017-ffca652a-5b7c-4c14-901e-e1f48a7430e0.gif)

**Comment by robotechalger** [comment]
me too !  any solutons ?

**Comment by cesar-bsd-com-br** [comment]
> me too ! any solutons ?

Same problem here: in version 16.0.5 this bug still remains.
